export enum ActionEnum {
  USER_AUTH = 'user_auth',
  USER_LOGOUT = 'user_logout',
  USER_FORGOT_PASSWORD = 'user_forgot_password',
  USER_REGISTER = 'user_register',
  USER_RESET_PASSWORD = 'user_reset_password',
  USER_CREATE_PRODUCT = 'user_create_product',
  USER_DELETE_PRODUCT = 'user_delete_product',
  USER_UPDATE_PRODUCT = 'user_update_product',
  USER_CART_CREATE = 'create_user_cart',
  USER_CART_UPDATE = 'update_user_cart',
  USER_CART_DELETE = 'delete_user_cart',
  USER_CART_DELETE_PRODUCT = 'delete_product_in_user_cart',
  USER_ORDER_CREATE = 'create_user_order',
  USER_ORDER_UPDATE = 'update_user_order',
  USER_ORDER_DELETE = 'delete_user_order',
  USER_ORDER_CONFIRMED = 'confirm_user_order',
  CATEGORY_CREATE = 'create_category',
  SUB_CATEGORY_CREATE = 'create_sub_category',
  SUB_SUB_CATEGORY_CREATE = 'create_sub_sub_category',
  ADD_SUB_CATEGORY = 'add_sub_category_to_category',
  ADD_SUB_SUB_CATEGORY = 'add_sub_sub_category_to_sub_category',

}
